### ISSUE TITLE
闹钟提醒问题

### ISSUE THREAD

**Issue by ScienceZone** [sysdzw/WeNote#1]
设置提醒对常用电脑的人有一定意义，但是我认为有意义的提醒应该死设定指定日期指定时间段提醒，不然谁会计算应该多少天多少小时之后提醒呢？！一般是有某件事需要在某天需要便笺出现在桌面上提醒自己一下去处理，比如10月1日晚上七点看新闻联播，所以可以设置便笺在10月1日打开电脑时在桌面出现提醒，截至晚上7点后多久消失，但是如果是截至提醒消失时间后再打开电脑，也可以出现提醒可能错过了某事。希望继续更新改进！
标题应该删除“闹钟”，无法更改了。

**Comment by sysdzw** [comment]
已经加上设置截止日期的功能了。
