### ISSUE TITLE
字体大小设置在哪里

### ISSUE THREAD

**Issue by mtdsj** [sysdzw/WeNote#3]
软件很好用，符合很多人对便签的要求，比如嵌入桌面功能。
但是字体大小设置在哪里？27寸屏幕下字体特别小，通过Ctrl键+鼠标滚轮调大后，下次开机又恢复到大约10px的字体

**Comment by sysdzw** [comment]
没考虑到字号字体问题哦。后面可以考虑加上




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vladimir ***@***.***&gt;; 
发送时间: 2024年10月25日(星期五) 中午12:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [sysdzw/WeNote] 字体大小设置在哪里 (Issue #3)














 
软件很好用，符合很多人对便签的要求，比如嵌入桌面功能。
 但是字体大小设置在哪里？27寸屏幕下字体特别小，通过Ctrl键+鼠标滚轮调大后，下次开机又恢复到大约10px的字体

**Comment by sysdzw** [comment]
已经更新到右键菜单里了。
![image](https://github.com/user-attachments/assets/742ac3d8-3b18-44ff-9f92-2c66145f92e4)

**Comment by mtdsj** [comment]
速度快，感谢！
